require 'rest-client'
require 'bitpagos/client'
require 'bitpagos/errors/generic_error'
require 'bitpagos/errors/invalid_api_key'
require 'bitpagos/errors/invalid_transaction_type'
require 'bitpagos/errors/unauthorized'
